version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:
      - 8080:8080
    restart: always

#  database:
#    image: postgres:12-alpine
#    env_file:
#      - .env.postgres
#    restart: always
#    expose:
#      - 5432
#    volumes:
#      - ${DATA_DIR}/postgresql:/var/lib/postgresql/dat
