version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: always

  database:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_DB=fbk_task
      - POSTGRES_PASSWORD=hello_friend
      - DATA_DIR=/data/postgres
    expose:
      - 5432
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
