version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:1.17.8-alpine
    restart: always
    depends_on:
      - app
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  postgres:
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
