version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    depends_on:
      - database
    restart: always

  nginx:
    image: nginx:1.17.8-alpine
    restart: always
    depends_on:
      - backend
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  database:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_DB=fbk_task
      - POSTGRES_PASSWORD=hello_friend
      - DATA_DIR=/data/postgres
    expose:
      - 5432
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
